# Site settings
title: Xion345 Blog 
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xion345.github.io" # the base hostname & protocol for your site
twitter_username: _Xion345 
github_username: Xion345

# Build settings
markdown: kramdown
