# Site settings
title: Fabien Andre's Blog
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fandre90.github.io" # the base hostname & protocol for your site
twitter_username: fandre90_
github_username: fandre90

# Build settings
markdown: kramdown
